instanceUrl: null
targetUsername: null
msTeamsWebhookUrl: null
installedPackages:
  - Id: 0A38b000001qso8CAA
    SubscriberPackageId: 03330000000wDAbAAM
    SubscriberPackageName: Salesforce Connected Apps
    SubscriberPackageNamespace: sf_com_apps
    SubscriberPackageVersionId: 04t30000001DUvrAAG
    SubscriberPackageVersionName: Winter '16
    SubscriberPackageVersionNumber: 1.7.0.1
  - Id: 0A38b000001qso9CAA
    SubscriberPackageId: 0336g0000004k1fAAA
    SubscriberPackageName: Trailhead Playground
    SubscriberPackageNamespace: trlhdtips
    SubscriberPackageVersionId: 04t6g000008C5dNAAS
    SubscriberPackageVersionName: Trailhead Playground App - Spring 2022 (v1.9)
    SubscriberPackageVersionNumber: 1.9.0.1
