name: build-ubuntu
on:
  push:
    paths:
      - force-app/**
      - .github/workflows/build-ubuntu.yml
    branches:
      - hardis/**
      - dev/**
      - fix/**
  # workflow_call:
  #   inputs:
  #     config-path:
  #       required: true
  #       type: string
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      - name: install salesforce cli
        run: |
          npm install @salesforce/cli --global
          sf version