name: Cleanup integration
on:
  workflow_call:
jobs:
  cleanup:
    name: Cleanup files and folders
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - name: Delete auth file
        run: |
          if [ -f ./INTEGRATION_URL ]; then
            rm ./INTEGRATION_URL.txt
          fi
      - name: Delete changed-sources dir
        run: if [ -d changed-sources]; then
          rm -rf changed-sources
          fi
