name: build-ubuntu
on:
  workflow_call:
  push:
    paths:
      - .github/workflows/pr-integration.yml
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo hi
