name: pr-to-pipeline-branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - force-app/**
    branches:
      - integration
      - uat
      - pre-prod
env:
  SFDX_ENV: ${{ github.base_ref }}

jobs:
  dry-run-project-to-env:
    name: Dry run - project to env
    permissions: write-all
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use JDK
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: "~/.npm" # npm cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Authenticate using secret
        run: |
          echo ${{secrets.SFDX_URL}} > ./SFDX_URL.txt
          npx sf auth sfdxurl store --sfdx-url-file ./SFDX_URL.txt --alias ag-target --set-default

      - name: Create tmp dir
        run: mkdir tmp

      - name: Deployment dry run with local tests
        id: deploy-dry-run
        run: |
          if [ -d force-app ]; then
            npx sf project deploy start --source-dir force-app --test-level RunLocalTests --json --dry-run --concise > tmp/results.json
          fi

      - uses: actions/setup-python@v4
        if: ${{ failure() && steps.deploy-dry-run.conclusion == 'failure' }}
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install python dependencies
        if: ${{ failure() && steps.deploy-dry-run.conclusion == 'failure' }}
        run: |
          pip -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Handle dry run failure
        if: ${{ failure() && steps.deploy-dry-run.conclusion == 'failure' }}
        run: |
          python scripts/ag/py.py --dry-run-failure --results-file tmp/results.json
