name: pr-to-pipeline-branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - force-app/**
    branches:
      - integration
      - uat
      - pre-prod
env:
  SFDX_ENV: ${{ github.base_ref }}

jobs:
  dry-run-project-to-env:
    name: Dry run - project to env
    permissions: write-all
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use JDK
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: "~/.npm" # npm cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Authenticate using secret
        run: echo ${{secrets.SFDX_URL}} > ./SFDX_URL.txt
          npx sf auth sfdxurl store --sfdx-url-file ./SFDX_URL.txt --alias ag-target --set-default

      - name: Deployment dry run with local tests
        run: |
          if [ -d force-app ]; then
            npx sf project deploy start --source-dir force-app --dry-run --test-level RunLocalTests --json
          fi
