name: push-to-dev-branch
on:
  workflow_dispatch:
  push:
    paths:
      - force-app/**
    branches:
      - hardis/**
      - dev/**
      - fix/**

jobs:
  dry-run-delta-to-integration:
    name: Dry run - delta to integration
    permissions: write-all
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"
          check-latest: true

      - name: Authenticate using secret
        run: |
          echo ${{secrets.SFDX_URL}} > ./SFDX_URL.txt
          npx sf auth sfdxurl store --sfdx-url-file ./SFDX_URL.txt --alias ag-target --set-default

      - name: Scan code
        run: |
          mkdir -p changed-sources
          npx sf scanner run --format sarif --target 'changed-sources/**/*.cls' --projectdir changed-sources --category 'Design,Best Practices,Performance,Code Style,Security' --outfile changed-sources/apexScanResults.sarif --loglevel DEBUG --verbose

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: changed-sources/apexScanResults.sarif

      - name: Create delta package
        run: |
          mkdir -p changed-sources
          npx sf sgd source delta --to HEAD --from HEAD^ --output changed-sources --generate-delta --source force-app

      - name: Create tmp dir
        run: mkdir tmp

      - name: Deployment dry run with local tests
        id: deploy-dry-run
        run: |
          if [ -d changed-sources/force-app ]; then
            npx sf project deploy start --source-dir changed-sources/force-app --test-level RunLocalTests --json --dry-run --concise > tmp/results.json
          fi

      - uses: actions/setup-python@v4
        if: ${{ failure() && steps.deploy-dry-run.conclusion == 'failure' }}
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install python dependencies
        if: ${{ failure() && steps.deploy-dry-run.conclusion == 'failure' }}
        run: |
          pip -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Handle dry run failure
        if: ${{ failure() && steps.deploy-dry-run.conclusion == 'failure' }}
        run: |
          python scripts/ag/py.py --dry-run-failure --results-file tmp/results.json
