name: Scan Apex classes
on:
  workflow_call:
jobs:
  scan:
    name: Scan Apex classes
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - name: Add changed-sources dir if needed
        run: mkdir -p changed-sources
      - name: Scan code
        run: sf scanner run --format sarif --target 'changed-sources/**/*.cls' --projectdir changed-sources --category 'Design,Best Practices,Performance,Code Style,Security' --outfile changed-sources/apexScanResults.sarif --loglevel DEBUG --verbose
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: changed-sources/apexScanResults.sarif
